CREATE TABLE superstore_silver.silver.people_scd2 (
  composite_key STRING,
  region STRING,
  person STRING,
  __MERGE_JOIN_HASH_KEY BIGINT,
  __MERGE_ROW_CHG_HIST_HASH_KEY BIGINT,
  __VRSN_START_DT DATE,
  __VRSN_END_DT DATE,
  __VRSN_CURR_FLG STRING,
  __MERGE_CREATE_TS TIMESTAMP,
  __MERGE_UPDATE_TS TIMESTAMP
)